version: "3.9"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_root_username
      MONGO_INITDB_ROOT_PASSWORD: your_root_password



volumes:
  mongodb-data:
